### PR TITLE
Resolving http2 problem

### PR DESCRIPTION
**Pull request by plel**
should resolve issue #49

### CODE REVIEW

**Comment by bjoern-flagbit** [comment]
Corresponding ticket on magento2 github:
https://github.com/magento/magento2/issues/19441

**Comment by josefbehr** [comment]
Would you be willing to make this into a PR for magento core?

**Comment by bjoern-flagbit** [comment]
Like I know this will be fixed in magento 2.3 ? But I'm not 100% sure.

**Comment by josefbehr** [comment]
@bjoern-flagbit not to my knowledge

**Pull request merged**
